import { BeeperMessage, Draft, CrmContactProfile, CrmTag, KanbanCard } from '@/lib/types';
import { ChatInfo } from '@/lib/beeper/types';

// ============================================
// DEMO DATA: Creator managing fan DMs
// Scenario: A tech YouTuber / content creator with ~500K followers
// managing DMs across Instagram, Twitter/X, Telegram, WhatsApp
// ============================================

const now = new Date();
const ago = (minutes: number) => new Date(now.getTime() - minutes * 60 * 1000).toISOString();

// ============================================
// TAGS
// ============================================
export const demoTags: Record<string, CrmTag> = {
  'tag-superfan': { id: 'tag-superfan', name: 'Superfan', color: '#f43f5e', createdAt: ago(10000) },
  'tag-brand': { id: 'tag-brand', name: 'Brand Deal', color: '#8b5cf6', createdAt: ago(10000) },
  'tag-collab': { id: 'tag-collab', name: 'Collab', color: '#3b82f6', createdAt: ago(10000) },
  'tag-lead': { id: 'tag-lead', name: 'Lead', color: '#f59e0b', createdAt: ago(10000) },
  'tag-vip': { id: 'tag-vip', name: 'VIP', color: '#10b981', createdAt: ago(10000) },
  'tag-press': { id: 'tag-press', name: 'Press', color: '#6366f1', createdAt: ago(10000) },
};

// ============================================
// AVATARS (using UI Faces style placeholder URLs)
// ============================================
export const demoAvatars: Record<string, string> = {
  'instagram:sarah_designs': 'https://i.pravatar.cc/150?img=1',
  'twitter:techbro_mike': 'https://i.pravatar.cc/150?img=3',
  'telegram:jenny_wu': 'https://i.pravatar.cc/150?img=5',
  'instagram:nike_partnerships': 'https://i.pravatar.cc/150?img=7',
  'whatsapp:alex_kumar': 'https://i.pravatar.cc/150?img=8',
  'twitter:podcast_lisa': 'https://i.pravatar.cc/150?img=9',
  'instagram:mark_editor': 'https://i.pravatar.cc/150?img=11',
  'telegram:fans_group': 'https://i.pravatar.cc/150?img=12',
  'whatsapp:mom': 'https://i.pravatar.cc/150?img=32',
  'instagram:brand_notion': 'https://i.pravatar.cc/150?img=15',
  'twitter:fan_carlos': 'https://i.pravatar.cc/150?img=14',
  'linkedin:recruiter_amy': 'https://i.pravatar.cc/150?img=16',
  'instagram:photographer_jules': 'https://i.pravatar.cc/150?img=20',
  'telegram:dev_community': 'https://i.pravatar.cc/150?img=22',
  'whatsapp:manager_ryan': 'https://i.pravatar.cc/150?img=51',
  'instagram:fan_priya': 'https://i.pravatar.cc/150?img=23',
  'twitter:journalist_ben': 'https://i.pravatar.cc/150?img=52',
  // Sent message chats
  'instagram:fan_recent_1': 'https://i.pravatar.cc/150?img=25',
  'twitter:fan_recent_2': 'https://i.pravatar.cc/150?img=33',
  'whatsapp:friend_recent': 'https://i.pravatar.cc/150?img=53',
  'telegram:collab_reply': 'https://i.pravatar.cc/150?img=56',
};

// ============================================
// CHAT INFO
// ============================================
export const demoChatInfo: Record<string, ChatInfo> = {
  'instagram:sarah_designs': { isGroup: false, title: 'Sarah Chen' },
  'twitter:techbro_mike': { isGroup: false, title: 'Mike Torres' },
  'telegram:jenny_wu': { isGroup: false, title: 'Jenny Wu' },
  'instagram:nike_partnerships': { isGroup: false, title: 'Nike Partnerships' },
  'whatsapp:alex_kumar': { isGroup: false, title: 'Alex Kumar' },
  'twitter:podcast_lisa': { isGroup: false, title: 'Lisa Park' },
  'instagram:mark_editor': { isGroup: false, title: 'Mark Johnson' },
  'telegram:fans_group': { isGroup: true, title: 'Creator Community' },
  'whatsapp:mom': { isGroup: false, title: 'Mom' },
  'instagram:brand_notion': { isGroup: false, title: 'Notion' },
  'twitter:fan_carlos': { isGroup: false, title: 'Carlos Rivera' },
  'linkedin:recruiter_amy': { isGroup: false, title: 'Amy Liu' },
  'instagram:photographer_jules': { isGroup: false, title: 'Jules Martinez' },
  'telegram:dev_community': { isGroup: true, title: 'Dev Community' },
  'whatsapp:manager_ryan': { isGroup: false, title: 'Ryan (Manager)' },
  'instagram:fan_priya': { isGroup: false, title: 'Priya Sharma' },
  'twitter:journalist_ben': { isGroup: false, title: 'Ben Wright' },
  // Sent message chats
  'instagram:fan_recent_1': { isGroup: false, title: 'Zoe Taylor' },
  'twitter:fan_recent_2': { isGroup: false, title: 'Dev Patel' },
  'whatsapp:friend_recent': { isGroup: false, title: 'Jake Wilson' },
  'telegram:collab_reply': { isGroup: false, title: 'Ash Nakamura' },
};

// ============================================
// UNREAD MESSAGES (from fans/brands/contacts)
// ============================================
export const demoUnreadMessages: BeeperMessage[] = [
  {
    id: 'msg-1',
    chatId: 'instagram:sarah_designs',
    accountId: 'acc-instagram',
    senderId: 'sarah_designs',
    senderName: 'Sarah Chen',
    text: "Hey! I've been following your channel for 2 years and your latest video on AI tools completely changed how I work. Would love to collaborate on a design systems video 🎨",
    timestamp: ago(12),
    isFromMe: false,
    isRead: false,
    platform: 'instagram',
    unreadCount: 2,
  },
  {
    id: 'msg-2',
    chatId: 'twitter:techbro_mike',
    accountId: 'acc-twitter',
    senderId: 'techbro_mike',
    senderName: 'Mike Torres',
    text: 'yo your take on the new MacBook Pro was spot on. you should do a video comparing it to the Framework laptop',
    timestamp: ago(25),
    isFromMe: false,
    isRead: false,
    platform: 'twitter',
    unreadCount: 1,
  },
  {
    id: 'msg-3',
    chatId: 'telegram:jenny_wu',
    accountId: 'acc-telegram',
    senderId: 'jenny_wu',
    senderName: 'Jenny Wu',
    text: "Quick question - what mic do you use for your voiceovers? The audio quality in your latest video was insane 🎙️",
    timestamp: ago(45),
    isFromMe: false,
    isRead: false,
    platform: 'telegram',
    unreadCount: 1,
  },
  {
    id: 'msg-4',
    chatId: 'instagram:nike_partnerships',
    accountId: 'acc-instagram',
    senderId: 'nike_partnerships',
    senderName: 'Nike Partnerships',
    text: "Hi! We're launching a new tech-meets-sport campaign and think your audience would be a great fit. Would love to discuss a potential partnership. Budget is $15K for a dedicated video.",
    timestamp: ago(90),
    isFromMe: false,
    isRead: false,
    platform: 'instagram',
    unreadCount: 1,
  },
  {
    id: 'msg-5',
    chatId: 'whatsapp:alex_kumar',
    accountId: 'acc-whatsapp',
    senderId: 'alex_kumar',
    senderName: 'Alex Kumar',
    text: 'bro the editing in that last video was NEXT LEVEL. how long did the motion graphics take?',
    timestamp: ago(120),
    isFromMe: false,
    isRead: false,
    platform: 'whatsapp',
    unreadCount: 3,
  },
  {
    id: 'msg-6',
    chatId: 'twitter:podcast_lisa',
    accountId: 'acc-twitter',
    senderId: 'podcast_lisa',
    senderName: 'Lisa Park',
    text: "Hey, I host the Creative Momentum podcast (250K listeners). Would love to have you on to talk about building a YouTube channel from scratch. Available next week?",
    timestamp: ago(180),
    isFromMe: false,
    isRead: false,
    platform: 'twitter',
    unreadCount: 1,
  },
  {
    id: 'msg-7',
    chatId: 'instagram:mark_editor',
    accountId: 'acc-instagram',
    senderId: 'mark_editor',
    senderName: 'Mark Johnson',
    text: 'The color grading tutorial saved my project!! Just got my first freelance client because of it 🙏',
    timestamp: ago(240),
    isFromMe: false,
    isRead: false,
    platform: 'instagram',
    unreadCount: 1,
  },
  {
    id: 'msg-8',
    chatId: 'telegram:fans_group',
    accountId: 'acc-telegram',
    senderId: 'community_member',
    senderName: 'Creator Community',
    text: 'Does anyone know when the next livestream is? The last Q&A was so helpful',
    timestamp: ago(300),
    isFromMe: false,
    isRead: false,
    platform: 'telegram',
    unreadCount: 14,
    isGroup: true,
  },
  {
    id: 'msg-9',
    chatId: 'whatsapp:mom',
    accountId: 'acc-whatsapp',
    senderId: 'mom',
    senderName: 'Mom',
    text: 'Your dad and I watched your new video! So proud of you ❤️ Also remember dinner Sunday at 6',
    timestamp: ago(360),
    isFromMe: false,
    isRead: false,
    platform: 'whatsapp',
    unreadCount: 2,
  },
  {
    id: 'msg-10',
    chatId: 'instagram:brand_notion',
    accountId: 'acc-instagram',
    senderId: 'brand_notion',
    senderName: 'Notion',
    text: "We loved your productivity setup video! Would you be interested in being a Notion Ambassador? We'd send you early access to new features + sponsor 3 videos.",
    timestamp: ago(420),
    isFromMe: false,
    isRead: false,
    platform: 'instagram',
    unreadCount: 1,
  },
  {
    id: 'msg-11',
    chatId: 'twitter:fan_carlos',
    accountId: 'acc-twitter',
    senderId: 'fan_carlos',
    senderName: 'Carlos Rivera',
    text: 'Your video literally made me switch careers into tech. Just got my first dev job. THANK YOU 🚀',
    timestamp: ago(480),
    isFromMe: false,
    isRead: false,
    platform: 'twitter',
    unreadCount: 1,
  },
  {
    id: 'msg-12',
    chatId: 'instagram:photographer_jules',
    accountId: 'acc-instagram',
    senderId: 'photographer_jules',
    senderName: 'Jules Martinez',
    text: "I'm a photographer based in LA - would love to shoot your next thumbnail/cover photos. Here's my portfolio",
    timestamp: ago(600),
    isFromMe: false,
    isRead: false,
    platform: 'instagram',
    unreadCount: 1,
    attachments: [{ type: 'img', mimeType: 'image/jpeg', fileName: 'portfolio.jpg' }],
  },
  {
    id: 'msg-17',
    chatId: 'instagram:fan_priya',
    accountId: 'acc-instagram',
    senderId: 'fan_priya',
    senderName: 'Priya Sharma',
    text: 'Your video on imposter syndrome really resonated with me. Starting my own channel because of you!',
    timestamp: ago(540),
    isFromMe: false,
    isRead: false,
    platform: 'instagram',
    unreadCount: 1,
  },
  {
    id: 'msg-18',
    chatId: 'twitter:journalist_ben',
    accountId: 'acc-twitter',
    senderId: 'journalist_ben',
    senderName: 'Ben Wright',
    text: "Hi, I'm writing a piece for The Verge on the creator economy. Would love a quick 15-min interview about your experience scaling content across platforms.",
    timestamp: ago(660),
    isFromMe: false,
    isRead: false,
    platform: 'twitter',
    unreadCount: 1,
  },
];

// ============================================
// DRAFTS (AI-generated replies in your voice)
// ============================================
export const demoDrafts: Draft[] = [
  {
    id: 'draft-1',
    originalMessageId: 'msg-13',
    chatId: 'linkedin:recruiter_amy',
    accountId: 'acc-linkedin',
    recipientName: 'Amy Liu',
    originalText: 'Hi! I represent a Series B startup looking for a Head of Content. Your YouTube growth from 0 to 500K is exactly what we need. Interested in chatting?',
    draftText: "Hey Amy! Appreciate you reaching out - that sounds like an interesting role. I'm pretty focused on the creator side right now but always happy to chat. Want to grab a quick coffee call next week?",
    platform: 'linkedin',
    avatarUrl: 'https://i.pravatar.cc/150?img=16',
    createdAt: ago(30),
    updatedAt: ago(30),
  },
  {
    id: 'draft-2',
    originalMessageId: 'msg-14',
    chatId: 'telegram:dev_community',
    accountId: 'acc-telegram',
    recipientName: 'Dev Community',
    originalText: 'Hey, is the next coding challenge this Friday? The React one last month was great',
    draftText: "Yep! This Friday at 7pm EST. We're doing a full-stack challenge this time - Next.js + Postgres. Prize pool is $500 in GitHub sponsors. Drop a 🔥 if you're in!",
    platform: 'telegram',
    avatarUrl: 'https://i.pravatar.cc/150?img=22',
    isGroup: true,
    createdAt: ago(15),
    updatedAt: ago(15),
  },
  {
    id: 'draft-3',
    originalMessageId: 'msg-15',
    chatId: 'whatsapp:manager_ryan',
    accountId: 'acc-whatsapp',
    recipientName: 'Ryan (Manager)',
    originalText: 'Notion just emailed about the ambassador deal - they want 3 videos over 6 months at $8K each. Thoughts?',
    draftText: "That's solid! $24K for 3 vids + early access to features is a great deal. I already use Notion so it's authentic. Let's counter with $10K per video since we'd also promote on socials. Can you draft the reply?",
    platform: 'whatsapp',
    avatarUrl: 'https://i.pravatar.cc/150?img=51',
    createdAt: ago(10),
    updatedAt: ago(10),
  },
];

// ============================================
// SENT MESSAGES (recently replied to)
// ============================================
export const demoSentMessages: BeeperMessage[] = [
  {
    id: 'sent-1',
    chatId: 'instagram:fan_recent_1',
    accountId: 'acc-instagram',
    senderId: 'me',
    senderName: 'Zoe Taylor',
    text: 'Thanks so much!! That means a lot. The key is consistency - even when no one is watching 🙌',
    timestamp: ago(60),
    isFromMe: true,
    isRead: true,
    platform: 'instagram',
    chatName: 'Zoe Taylor',
  },
  {
    id: 'sent-2',
    chatId: 'twitter:fan_recent_2',
    accountId: 'acc-twitter',
    senderId: 'me',
    senderName: 'Dev Patel',
    text: "haha glad you liked it! the Framework comparison is actually already in the pipeline 👀",
    timestamp: ago(120),
    isFromMe: true,
    isRead: true,
    platform: 'twitter',
    chatName: 'Dev Patel',
  },
  {
    id: 'sent-3',
    chatId: 'whatsapp:friend_recent',
    accountId: 'acc-whatsapp',
    senderId: 'me',
    senderName: 'Jake Wilson',
    text: "Yeah let's do Thursday! I'll book us that new ramen place. 7pm work?",
    timestamp: ago(180),
    isFromMe: true,
    isRead: true,
    platform: 'whatsapp',
    chatName: 'Jake Wilson',
  },
  {
    id: 'sent-4',
    chatId: 'telegram:collab_reply',
    accountId: 'acc-telegram',
    senderId: 'me',
    senderName: 'Ash Nakamura',
    text: "Just sent over the B-roll files! Let me know if the resolution is good enough for 4K",
    timestamp: ago(240),
    isFromMe: true,
    isRead: true,
    platform: 'telegram',
    chatName: 'Ash Nakamura',
  },
];

// ============================================
// CRM CONTACTS
// ============================================
function makeContact(
  chatId: string,
  displayName: string,
  platform: string,
  opts: Partial<CrmContactProfile> = {}
): CrmContactProfile {
  return {
    id: `contact-${chatId}`,
    displayName,
    avatarUrl: demoAvatars[chatId],
    platformLinks: [
      {
        platform,
        chatId,
        accountId: `acc-${platform}`,
        displayName,
        avatarUrl: demoAvatars[chatId],
        addedAt: ago(10000),
      },
    ],
    tags: [],
    createdAt: ago(10000),
    updatedAt: ago(100),
    ...opts,
  };
}

export const demoContacts: Record<string, CrmContactProfile> = {
  'contact-instagram:sarah_designs': makeContact('instagram:sarah_designs', 'Sarah Chen', 'instagram', {
    tags: ['tag-collab', 'tag-superfan'],
    totalMessageCount: 47,
    messagesReceived: 32,
    messagesSent: 15,
    lastInteractionAt: ago(12),
    role: 'UX Designer',
    company: 'Figma',
  }),
  'contact-twitter:techbro_mike': makeContact('twitter:techbro_mike', 'Mike Torres', 'twitter', {
    tags: ['tag-superfan'],
    totalMessageCount: 23,
    messagesReceived: 18,
    messagesSent: 5,
    lastInteractionAt: ago(25),
  }),
  'contact-telegram:jenny_wu': makeContact('telegram:jenny_wu', 'Jenny Wu', 'telegram', {
    tags: ['tag-superfan'],
    totalMessageCount: 8,
    messagesReceived: 6,
    messagesSent: 2,
    lastInteractionAt: ago(45),
  }),
  'contact-instagram:nike_partnerships': makeContact('instagram:nike_partnerships', 'Nike Partnerships', 'instagram', {
    tags: ['tag-brand', 'tag-vip'],
    totalMessageCount: 4,
    messagesReceived: 3,
    messagesSent: 1,
    lastInteractionAt: ago(90),
    company: 'Nike',
    role: 'Creator Partnerships',
  }),
  'contact-whatsapp:alex_kumar': makeContact('whatsapp:alex_kumar', 'Alex Kumar', 'whatsapp', {
    tags: ['tag-superfan'],
    totalMessageCount: 89,
    messagesReceived: 52,
    messagesSent: 37,
    lastInteractionAt: ago(120),
  }),
  'contact-twitter:podcast_lisa': makeContact('twitter:podcast_lisa', 'Lisa Park', 'twitter', {
    tags: ['tag-collab', 'tag-press'],
    totalMessageCount: 6,
    messagesReceived: 4,
    messagesSent: 2,
    lastInteractionAt: ago(180),
    role: 'Podcast Host',
    company: 'Creative Momentum',
  }),
  'contact-instagram:mark_editor': makeContact('instagram:mark_editor', 'Mark Johnson', 'instagram', {
    tags: ['tag-superfan'],
    totalMessageCount: 12,
    messagesReceived: 9,
    messagesSent: 3,
    lastInteractionAt: ago(240),
  }),
  'contact-telegram:fans_group': makeContact('telegram:fans_group', 'Creator Community', 'telegram', {
    isGroup: true,
    totalMessageCount: 342,
    messagesReceived: 310,
    messagesSent: 32,
    lastInteractionAt: ago(300),
  }),
  'contact-whatsapp:mom': makeContact('whatsapp:mom', 'Mom', 'whatsapp', {
    tags: ['tag-vip'],
    totalMessageCount: 156,
    messagesReceived: 89,
    messagesSent: 67,
    lastInteractionAt: ago(360),
  }),
  'contact-instagram:brand_notion': makeContact('instagram:brand_notion', 'Notion', 'instagram', {
    tags: ['tag-brand', 'tag-vip'],
    totalMessageCount: 7,
    messagesReceived: 5,
    messagesSent: 2,
    lastInteractionAt: ago(420),
    company: 'Notion',
    role: 'Creator Relations',
  }),
  'contact-twitter:fan_carlos': makeContact('twitter:fan_carlos', 'Carlos Rivera', 'twitter', {
    tags: ['tag-superfan'],
    totalMessageCount: 15,
    messagesReceived: 12,
    messagesSent: 3,
    lastInteractionAt: ago(480),
  }),
  'contact-linkedin:recruiter_amy': makeContact('linkedin:recruiter_amy', 'Amy Liu', 'linkedin', {
    tags: ['tag-lead'],
    totalMessageCount: 3,
    messagesReceived: 2,
    messagesSent: 1,
    lastInteractionAt: ago(550),
    role: 'Head of Talent',
    company: 'Stealth Startup',
  }),
  'contact-instagram:photographer_jules': makeContact('instagram:photographer_jules', 'Jules Martinez', 'instagram', {
    tags: ['tag-collab'],
    totalMessageCount: 5,
    messagesReceived: 4,
    messagesSent: 1,
    lastInteractionAt: ago(600),
    role: 'Photographer',
  }),
  'contact-telegram:dev_community': makeContact('telegram:dev_community', 'Dev Community', 'telegram', {
    isGroup: true,
    totalMessageCount: 215,
    messagesReceived: 198,
    messagesSent: 17,
    lastInteractionAt: ago(700),
  }),
  'contact-whatsapp:manager_ryan': makeContact('whatsapp:manager_ryan', 'Ryan (Manager)', 'whatsapp', {
    tags: ['tag-vip'],
    totalMessageCount: 234,
    messagesReceived: 120,
    messagesSent: 114,
    lastInteractionAt: ago(800),
    role: 'Talent Manager',
    company: 'Creative Mgmt',
  }),
  'contact-instagram:fan_priya': makeContact('instagram:fan_priya', 'Priya Sharma', 'instagram', {
    tags: ['tag-superfan'],
    totalMessageCount: 9,
    messagesReceived: 7,
    messagesSent: 2,
    lastInteractionAt: ago(540),
  }),
  'contact-twitter:journalist_ben': makeContact('twitter:journalist_ben', 'Ben Wright', 'twitter', {
    tags: ['tag-press', 'tag-vip'],
    totalMessageCount: 2,
    messagesReceived: 2,
    messagesSent: 0,
    lastInteractionAt: ago(660),
    role: 'Tech Reporter',
    company: 'The Verge',
  }),
};
